import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma'; // Use our Prisma client!

export async function POST(req: Request) {
  try {
    const { userAddress } = await req.json();

    if (!userAddress) {
      return NextResponse.json({ error: 'User address is required' }, { status: 400 });
    }

    // 1. Find the user in the database using their wallet address
    const user = await prisma.user.findUnique({
      where: { walletAddress: userAddress }
    });

    if (!user) {
      return NextResponse.json({ proposal: null, message: 'User not registered yet.' });
    }

    // 2. Fetch the absolute latest proposal generated by our 24/7 bot
    const latestProposal = await prisma.proposal.findFirst({
      where: { userId: user.id },
      orderBy: { createdAt: 'desc' } // Gets the newest one first
    });

    if (!latestProposal) {
      // Fallback if the bot hasn't triggered anything yet
      return NextResponse.json({ proposal: null, message: 'Market stable, no action required.' });
    }

    // 3. Return the live database signal to the UI!
    return NextResponse.json({
      proposal: {
        type: latestProposal.type, // e.g., "TRIM_WLD"
        description: latestProposal.description,
        expectedYield: latestProposal.expectedYield,
        txData: [] // In production, we attach the Morpho payload here
      }
    });

  } catch (error) {
    console.error('API Error:', error);
    return NextResponse.json({ error: 'Failed to fetch signal from database' }, { status: 500 });
  }
}