import { NextResponse } from 'next/server';
import { prisma } from '../../../lib/prisma';

export const dynamic = 'force-dynamic';

export async function POST(req: Request) {
  try {
    const { userId } = await req.json(); // The frontend passes the walletAddress here

    if (!userId) {
      return NextResponse.json({ error: 'Wallet address is required' }, { status: 400 });
    }

    // 1. Find the user in our database
    const user = await prisma.user.findUnique({
      where: { walletAddress: userId }
    });

    if (!user) {
      // If the user isn't in the DB yet, default to HOLD
      return NextResponse.json({ status: 'success', signal: 'HOLD', price: '0.420' });
    }

    // 2. Production Logic: Look for the latest AI proposal generated by your Render Daemon!
    const latestProposal = await prisma.proposal.findFirst({
      where: { 
        userId: user.id,
        status: 'PENDING_USER_APPROVAL' 
      },
      orderBy: { createdAt: 'desc' }
    });

    if (latestProposal) {
      // The Daemon fired a signal! Serve it directly to the user's phone.
      return NextResponse.json({
        status: 'success',
        signal: latestProposal.type, // e.g., 'TRIM_WLD' or 'BUY_WLD'
        price: '0.420',
        description: latestProposal.description,
        expectedYield: latestProposal.expectedYield
      });
    }

    // 3. Default state: Daemon hasn't fired because the market is stable.
    return NextResponse.json({
      status: 'success',
      signal: 'HOLD',
      price: '0.420'
    });

  } catch (error: any) {
    console.error('Production Agent API Error:', error.message);
    return NextResponse.json({ error: 'Database connection failed' }, { status: 500 });
  }
}